---
# Per environment values which override defaults in hmpps-suicide-risk-form-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: suicide-risk-form-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    NDELIUS-INTEGRATION-API_URL: "https://suicide-risk-form-and-delius-preprod.hmpps.service.justice.gov.uk"
    FRONTEND_URL: "https://suicide-risk-form-preprod.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - moj_cloud_platform
      - delius-preprod
      - mod-platform-live


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-suicide-risk-form-notifications
